project:
  type: website

website:
  title: "LaTeX Document"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
      - text: "References"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
